### ISSUE TITLE
Improve the error message for invalid contact points

### ISSUE THREAD

**Issue by vroyer** [datastax/messaging-connectors-commons#10]
Currently, when the contactPoints includes the CQL port in the configuration, the error message is not super clear, and many people  does not understand what's going wrong:

`05:09:43.039 [public/default/cassandra-source-testks-person-0] ERROR com.datastax.oss.pulsar.source.CassandraSource - Unrecoverable error:
com.datastax.oss.common.sink.ConfigException: Incorrect contactPoints: 10.101.32.81:9042
        at com.datastax.oss.common.sink.config.ContactPointsValidator.validateContactPoints(ContactPointsValidator.java:42) ~[messaging-connectors-commons-core-1.0.14.jar:?]
        at com.datastax.oss.cdc.CassandraClient.buildCqlSession(CassandraClient.java:106) ~[connector-1.0.1.jar:?]
        at com.datastax.oss.cdc.CassandraClient.<init>(CassandraClient.java:82) ~[connector-1.0.1.jar:?]
        at com.datastax.oss.pulsar.source.CassandraSource.initCassandraClient(CassandraSource.java:302) ~[pulsar-cassandra-source-1.0.1.jar:?]`

**Comment by yabinmeng** [comment]
@vroyer 

I don't think this is only an error message issue. The right format of a contact point should be <host_name_or_ip>:<port> instead of just <host_name_or_ip>. C* connection port (9042) is configurable and can be one different. Also when C* SSL/TLS is enabled, the default port is 9142.

**Comment by yabinmeng** [comment]
I may misunderstand this such that the contact points is designed only to have the host name or IP part without port. But it is a common practice to have both the host name or IP and port as part one single contact point string, such as in the following snippet from DataStax doc. It would be beneficial to respect this convention.

`// Add `application.conf` to your classpath with the following contents:
datastax-java-driver {
  basic {
    contact-points = [ "1.2.3.4:9042", "5.6.7.8:9042" ]
    load-balancing-policy.local-datacenter = datacenter1
  }
}`
